title: "Le dev, c'est di√®se"
description: "Veille, tutoriels .NET, Azure et plus"
author: "MattDevBzh"
baseurl: ""
url: "https://MattDevBzh.github.io"

theme: Cayman

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
